name: Post DEV.to Articles to Telegram

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get DEV.to Articles
        id: get_articles
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        run: |
          curl -X GET "https://dev.to/api/articles/me/published" \
            -H "api-key: $DEVTO_API_KEY" \
            -o devto_articles.json

      - name: Post to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LATEST_ARTICLE=$(jq -r '.[0]' devto_articles.json)
          TITLE=$(echo $LATEST_ARTICLE | jq -r '.title')
          URL=$(echo $LATEST_ARTICLE | jq -r '.url')
          MESSAGE="New article published: $TITLE\n$URL"
          curl -s --data "chat_id=$TELEGRAM_CHAT_ID&text=$MESSAGE" \
            "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
